server:
  port: 8085
spring:
  application:
    name: controller-logger-application
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

